### ISSUE TITLE
MixEffect companion module on raspberry pi

### ISSUE THREAD

**Issue by mazzopalazzo** [bitfocus/companion-module-tow-mixeffect#2]
Hi Johnny

Great work you're doing. Wanted to hear if you know if there's a companion beta build for raspberry pi with the native mixeffect module?

Best regards, Mads

**Comment by estilles** [comment]
@mazzopalazzo ... I will close this issue for now. If you still have any additional questions regarding this feel free to reach out to me or just reopen the issue and comment here.
