### ISSUE TITLE
Raspi?

### ISSUE THREAD

**Issue by derkleinemischi** [bitfocus/companion-module-tow-mixeffect#3]
Hi,
will there be a version for the Raspberry Pi as well?
Best Regards, Michael

**Comment by josephdadams** [comment]
If you are running the Companion Pi image, you can just run `sudo companion-update` but I don't remember if this pulls from the latest main branch or another branch. @jarodwsams can probably answer this

**Comment by estilles** [comment]
Hey @derkleinemischi, @josephdadams is right. If you're already running CompanionPi running `sudo companion-update` from the terminal should do the trick. If you haven't installed it yet, you should check out the [ComnpanionPi Documentation here](https://github.com/bitfocus/companion/wiki/CompanionPi-Documentation).

**Comment by estilles** [comment]
Oh .... @josephdadams, I just realized the latest version of the module `v1.1.1` hasn't been updated in the Companion core yet. It's still on `v1.0.0`. I requested an update from @JeffreyDavidsz last month on Slack, but I guess the Companion team has been busy. `v1.1.x` adds A LOT of new features. Is there any chance we can get it updated sometime soon?

**Comment by josephdadams** [comment]
boom done

**Comment by estilles** [comment]
Nice! Thanks @josephdadams!!!!!

**Comment by estilles** [comment]
Hey @derkleinemischi, running `sudo companion-update` should now update the module to `v1.1.1` on your CompanionPi. Let us know if it works for you.

**Comment by derkleinemischi** [comment]
Hi @estilles @josephdadams, Yessss, everything works fine! Thank you!!!

**Comment by estilles** [comment]
Thanks for the update @derkleinemischi. Glad everything's working fine. Closing this issue for now.
