### ISSUE TITLE
Missing 4 M/E Broadcast Studio 4K switcher

### ISSUE THREAD

**Issue by adamtow** [bitfocus/companion-module-tow-mixeffect#5]
The list of switcher models supported is missing the 4 M/E Broadcast Studio 4K. It's similar to the 2 M/E except that it has 4 Mix Effect Buses.

**Comment by estilles** [comment]
Thank @adamtow! I'll look into adding it.
https://www.blackmagicdesign.com/products/atem/techspecs/W-APS-10
