### ISSUE TITLE
Reopening: M/E picker menus don't show additional buses on supported switchers

### ISSUE THREAD

**Issue by TVcameras** [bitfocus/companion-module-tow-mixeffect#6]
On November 24th, Adam Tow wrote: 
     "Tried using the 2 M/E and the Constellation 8K. The M/E pickers only show M/E 1 and Selected M/E.
      They should show the correct number of Mix Effect Buses available for the switcher:
           2 M/E: 2
           4 M/E: 4
           Constellation 8K: 4"

This still doesn't work.  When trying to select inputs into keyers on M/Es 2-4, I am not able to select any M/E bus except M/E 1 (on the "Mix Effect Bus" drop down menu)..  Thank you Johnny!

**Comment by adamtow** [comment]
This was fixed in the 1.1.8 release of the module.
